package com.ufpor.app.shared.ifcclient;

/**
 * Created by Ehsan Barekati on 10/30/14.
 */
public enum IfcClientRoleEnum {
    SUPPLIER,
    MANUFACTURER,
    CONTRACTOR,
    SUBCONTRACTOR,
    ARCHITECT,
    STRUCTURALENGINEER,
    COSTENGINEER,
    CLIENT,
    BUILDINGOWNER,
    BUILDINGOPERATOR,
    MECHANICALENGINEER,
    ELECTRICALENGINEER,
    PROJECTMANAGER,
    FACILITIESMANAGER,
    CIVILENGINEER,
    COMMISSIONINGENGINEER,
    ENGINEER,
    OWNER,
    CONSULTANT,
    CONSTRUCTIONMANAGER,
    FIELDCONSTRUCTIONMANAGER,
    RESELLER,
    USERDEFINED
}
